#newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
fn_args_layout = "Compressed"
max_width = 116
chain_width = 90
fn_call_width = 90
struct_lit_width = 60
struct_variant_width = 50

unstable_features = true
#wrap_comments = true
#reorder_impl_items = true
format_code_in_doc_comments = true
#error_on_line_overflow = true
group_imports = "One"
imports_granularity = "Crate"
