[package]
name = "bevy_ecs_enum_filter_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
app = []
bevy = []
ecs = []

[dependencies]
syn = "2.0"
proc-macro2 = "1.0"
proc-macro-crate = "3.3"
quote = "1.0"
convert_case = "0.8.0"
